export const GET_PROGNOSIS_LIST_REQUEST = 'GET_PROGNOSIS_LIST_REQUEST'
export const GET_PROGNOSIS_LIST_REFRESH_REQUEST = 'GET_PROGNOSIS_LIST_REFRESH_REQUEST'
export const GET_PROGNOSIS_LIST_SUCCESS = 'GET_PROGNOSIS_LIST_SUCCESS'
export const GET_PROGNOSIS_LIST_FAIL = 'GET_PROGNOSIS_LIST_FAIL'

export const GET_PROGNOSIS_REQUEST = 'GET_PROGNOSIS_REQUEST'
export const GET_PROGNOSIS_REFRESH_REQUEST = 'GET_PROGNOSIS_REFRESH_REQUEST'
export const GET_PROGNOSIS_SUCCESS = 'GET_PROGNOSIS_SUCCESS'
export const GET_PROGNOSIS_FAIL = 'GET_PROGNOSIS_FAIL'

export const ADD_PROGNOSIS_REQUEST = 'ADD_PROGNOSIS_REQUEST'
export const ADD_PROGNOSIS_SUCCESS = 'ADD_PROGNOSIS_SUCCESS'
export const ADD_PROGNOSIS_FAIL = 'ADD_PROGNOSIS_FAIL'