export const AUTH_REQUEST = 'AUTH_REQUEST'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const INIT_AUTH_DATA_SUCCESS = 'INIT_AUTH_DATA_SUCCESS'

export const AUTH_FAIL = 'AUTH_FAIL'

