export const GET_TOURNAMENT_LIST_REQUEST = 'GET_TOURNAMENT_LIST_REQUEST'
export const GET_TOURNAMENT_LIST_SUCCESS = 'GET_TOURNAMENT_LIST_SUCCESS'
export const GET_TOURNAMENT_LIST_FAIL = 'GET_TOURNAMENT_LIST_FAIL'