export const GET_PROFILE_BETS_REQUEST = 'GET_PROFILE_BETS_REQUEST'
export const GET_PROFILE_BETS_SUCCESS = 'GET_PROFILE_BETS_SUCCESS'
export const GET_PROFILE_BETS_FAIL = 'GET_PROFILE_BETS_FAIL'

export const GET_PROFILE_BANK_REQUEST = 'GET_PROFILE_BANK_REQUEST'
export const GET_PROFILE_BANK_SUCCESS = 'GET_PROFILE_BANK_SUCCESS'
export const GET_PROFILE_BANK_FAIL = 'GET_PROFILE_BANK_FAIL'